---SUBSTRING

SELECT SUBSTRING(NAMESURNAME,1,4)SUBSTRING_,NAMESURNAME FROM USERS -- (column,1 ve 4 aralığı karaterleri , 

SELECT SUBSTRING(TELNR1,1,3) FROM USERS  --en çok hangi operatör kullanılıyor. 

SELECT SUBSTRING(BIRTHDATE,1,3) FROM USERS --VERI TIPINE DIKKAT  
 
---CHARINDEX

SELECT CHARINDEX('Z',NAMESURNAME,1),NAMESURNAME FROM USERS

---CONCAT
SELECT 'MERT'+'ALABAŞ'
SELECT 'MERT'+' '+'ALABAŞ'

SELECT CONCAT('MERT','ALABAŞ')
SELECT CONCAT('MERT',' ','ALABAŞ')

SELECT USERNAME_+' '+PASSWORD_ AS YENI,* FROM USERS

SELECT CONCAT(USERNAME_,' ',PASSWORD_)AS YENIKOLON, * FROM USERS

SELECT NAMESURNAME+'----------'+GENDER,* FROM USERS
SELECT CONCAT(NAMESURNAME,'-----',GENDER) FROM USERS


---LEFT,RIGHT,LEN

SELECT LEFT(BIRTHDATE,4)YIL,BIRTHDATE FROM USERS
SELECT RIGHT(BIRTHDATE,5),BIRTHDATE FROM USERS

SELECT RIGHT(EMAIL,16),EMAIL FROM USERS

SELECT LEN(USERNAME_),USERNAME_ FROM USERS

SELECT LEN(PASSWORD_),PASSWORD_ FROM USERS

----LTRIM,RTRIM

SELECT LTRIM(' MERT') FROM USERS--boşlukları kaldırır
SELECT RTRIM('MERT ')

-----LOWER,UPPER,REVERSE

SELECT LOWER(USERNAME_),USERNAME_ FROM USERS

SELECT LOWER(USERNAME_)KUCUK,UPPER(NAMESURNAME)BUYUKISIM,* FROM USERS

SELECT REVERSE(NAMESURNAME),NAMESURNAME FROM USERS


----YUVARLAMA: YASEMİN YUVARLA GETİR DEMİŞTİR. 

SELECT ROUND(TOTALPRICE,0),TOTALPRICE FROM ORDERS
SELECT FLOOR(TOTALPRICE) FROM ORDERS
SELECT CEILING(TOTALPRICE) FROM ORDERS


---TARİHSEL İŞLEMLER
--mm/dd/yyyy
SELECT CONVERT(varchar,DATE_,101)TARIH,DATE_ FROM ORDERS -- HANGİ VERİ TİĞİNE DÖNÜŞTÜRECEĞİN : VARCHAR  , 101 : 

--yyyy.mm.dd
select CONVERT(varchar,DATE_,102),DATE_ from ORDERS

---dd.mm.yyyy
select CONVERT(varchar,DATE_,104),DATE_ from ORDERS

---dd mon yyyy
select CONVERT(varchar,DATE_,106),DATE_ from ORDERS

--hh:mm:ss
select CONVERT(varchar,DATE_,112),DATE_ from ORDERS

--yyyymmdd
select CONVERT(varchar,DATE_,10),DATE_ from ORDERS




----DATEDIFF

select GETDATE()

select MAX(DATE_) from ORDERS

SELECT DATEDIFF(DAY,MAX(DATE_),GETDATE()) AS FARK,  MAX(DATE_) AS MAXDATE,    GETDATE() AS BUGUN 
FROM ORDERS

SELECT * FROM ORDERS WHERE CONVERT(varchar,DATE_,112)=CONVERT(varchar,getdate(),112)-1



----DATEADD
SELECT DATEADD(DAY,0,GETDATE()) AS YENITARIH,* FROM ORDERS  --ETL ZAMANI YAZILMIŞ OLUYOR 


---DATEPART :TARİHLERİ PARÇAMALA FONKSİYONUDUR. 
SELECT DATEPART(DAY,DATE_)GUN, DATEPART(YEAR,DATE_)YIL, DATEPART(MONTH,DATE_)AY, DATE_ FROM ORDERS;
SELECT * FROM ORDERS WHERE YEAR(DATE_)=2020 AND MONTH(DATE_)=3; -- Sorguda yapmak her zaman daha performans açısından avantajlıdır. 


----CASE WHEN 

SELECT 
	CASE 
	WHEN GENDER='K' then 'KADIN'
	WHEN GENDER='E' then 'ERKEK' 
	ELSE GENDER 
	END null  AS CINSIYETTANIM , GENDER 
FROM USERS

----------
ALTER TABLE USERS ADD  AGE INT ;
SELECT * FROM USERS 
UPDATE USERS
SET AGE = FLOOR(RAND(CHECKSUM(NEWID())) * (60 - 18 + 1)) + 18
WHERE AGE IS NULL;

SELECT
		CASE
		WHEN AGE BETWEEN 10 AND 30 THEN 'GENC'
		WHEN AGE BETWEEN 31 AND 59 THEN 'ORTA YASLI'
		ELSE 'YASLI'
		END AS YASGRUP,AGE
FROM USERS 




---- SUBQUERY 
SELECT * FROM USERS 
WHERE ID IN (SELECT USERID FROM ORDERS WHERE STATUS_='2')




 































